version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/
      - etc-letsencrypt:/etc/letsencrypt
    ports:
      - "80:80" 
      - "443:443"

certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - ./:/var/www/
    command: certonly --webroot --webroot-path=/var/www/html --email pavlenko.at@mail.ru --agree-tos --no-eff-email -d test.world-itech.ru