version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./_docker/nginx/:/etc/nginx/conf.d/
      - ./:/var/www/
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80" 
      - "443:443"

      
  php:
    image: php:8.2-fpm
    volumes:
      - ./:/var/www/