version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./:/var/www/
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80" 
      - "443:443"